version: "3"

services:
  redis:
    image: redis:6.0
    container_name: dev-redis
    platform: linux/x86_64
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
    networks:
      - middleware
  etcd:
    image: bitnami/etcd:latest
    container_name: dev-etcd
    platform: linux/x86_64
    restart: always
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    ports:
      - '2379:2379'
      - '2380:2380'
    networks:
      - middleware
  redis-cluster:
    image: grokzen/redis-cluster:latest
    container_name: dev-redis-cluster
    platform: linux/x86_64
    environment:
      - IP=0.0.0.0
      - STANDALONE=true
      - SENTINEL=true
    ports:
      - '7000-7005:7000-7005'
  nats:
    image: nats:latest
    container_name: dev-nats
    platform: linux/x86_64
    restart: always
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
networks:
  middleware:
    driver: bridge